sonar.projectKey=leninkart-product-service
sonar.projectName=LeninKart Product Service
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes,target/test-classes
sonar.exclusions=target/**
